apps = 'apps/scalable/'
places = 'places/scalable'
mimetypes = 'mimetypes/scalable'

# as tuplas devem seguir o padrão (origem, nome do ícone)

# --- apps (com algumas exceções) --------------------------------------------------
plain_folder_group = {
    'group_name': 'Folder-likes - Plain',
    'copies': [
        (apps, 'd3lphin'),
        (apps, 'org.kde.plasma.folder'),
        (apps, 'thunar-filemanager'),
        (apps, 'xfce-filemanager'),
        (apps, 'file-manager-blue'),
        (apps, 'com.system76.CosmicFiles'),
        (apps, 'file-manager'),
        (apps, 'folder_doc_q4os_startmenu'),
        (apps, 'org.kde.dolphin'),
        (apps, 'spacefm-blue'),
        (apps, 'dde-file-manager'),
        (apps, 'dolphin'),
        (apps, 'gnome-commander'),
        (apps, 'gnome-encfs-manager'),
        (apps, 'kfm'),
        (apps, 'nautilus'),
        (apps, 'nemo'),
        (apps, 'redhat-filemanager'),
        (apps, 'system-file-manager'),
        (apps, 'thunar'),
        (apps, 'Thunar'),
        (apps, 'user-file-manager'),
        (apps, 'mc'),
        (apps, 'MidnightCommander'),
        (apps, 'mucommander'),
        (apps, 'nautilus-actions-config-tool'),
        (apps, 'nautilus-actions'),
        (apps, 'org.gnome.files'),
        (apps, 'org.gnome.Files'),
        (apps, 'org.gnome.nautilus'),
        (apps, 'org.gnome.Nautilus'),
        (apps, 'org.kde.index'),
        (apps, 'org.xfce.filemanager'),
        (apps, 'org.xfce.panel.directorymenu'),
        (apps, 'org.xfce.thunar'),
        (apps, 'pcmanfm-qt'),
        (apps, 'spacefm'),
        (apps, 'fma-config-tool'),
        (apps, 'caja-actions'),
        (apps, 'com.yuenhoe.filedrawer'),
        (places, 'folder'),
        (places, 'folder_2'),
        (places, 'gnome-folder'),
        (places, 'gnome-fs-directory-accept'),
        (places, 'gnome-fs-directory'),
        (places, 'gtk-directory'),
        (places, 'inode-directory'),
        (places, 'stock_folder'),
        (mimetypes, 'inode-directory')
    ]
}

variations_group = {
    'group_name': 'Folder-likes - Variations',
    'copies': [
        (apps, 'AirPortUtility'),
        (apps, 'athena'),
        (apps, 'filezilla'),
        (apps, 'cs-network'),
        (apps, 'gnome-network-properties'),
        (apps, 'kali-wireless-attacks-trans'),
        (apps, 'kfoldersync'),
        (apps, 'xfe'),
        (apps, 'krusader_blue'),
        (apps, 'krusader_red'),
        (apps, 'krusader_root'),
        (apps, 'krusader_user'),
        (apps, 'linssid'),
        (apps, 'mate-netspeed-applet'),
        (apps, 'mate-network-properties'),
        (apps, 'nautilus-alt'),
        (apps, 'network-manager'),
        (apps, 'network-workgroup'),
        (apps, 'networkmanager'),
        (apps, 'org.kde.plasma.vault'),
        (apps, 'plasmavault'),
        (apps, 'wicd'),
        (apps, 'wicd-gtk'),
        (apps, 'wifi-radar'),
        (apps, 'winefile'),
        (apps, 'filemanager-actions'),
        (apps, 'Finder_w'),
    ]
}

derivations_group = {
    'group_name': 'Folder-likes - Derivations',
    'copies': [
        (apps, 'file-manager-green'),
        (apps, 'file-manager-red'),
        (apps, 'spacefm-green'),
        (apps, 'spacefm-red'),
        (apps, 'system-file-manager-root'),
        (places, 'folder-black'),
        (places, 'folder-blue'),
        (places, 'folder-brown'),
        (places, 'folder-cyan'),
        (places, 'folder-green'),
        (places, 'folder-grey'),
        (places, 'folder-magenta'),
        (places, 'folder-orange'),
        (places, 'folder-red'),
        (places, 'folder-violet'),
        (places, 'folder-yellow'),
    ]
}

# --- places --------------------------------------------------
folder_locked_group = {
    'group_name': 'Folder-likes - Locked',
    'copies': [
        (places, 'folder-locked'),
        (places, 'certificate-server'),
        (places, 'folder-ecrypted'),
        (places, 'folder-encrypted'),
    ]
}

folder_home_group = {
    'group_name': 'Folder-likes - Home',
    'copies': [
        (places, 'folder_home'),
        (places, 'folder-home'),
        (places, 'folder-home2'),
        (places, 'gnome-fs-home'),
        (places, 'gnome-home'),
        (places, 'user-home'),
        (places, 'user-home-drag-accept'),
        (places, 'user-home-open')
    ]
}

folder_favorites_group = {
    'group_name': 'Folder-likes - Favorites',
    'copies': [
        (places, 'folder-favorites'),
        (places, 'favorites'),
        (places, 'user-bookmarks'),
        (places, 'folder-bookmarks'),
        (places, 'folder-bookmark'),
        (places, 'gnome-fs-bookmark'),
        (places, 'stock_bookmark'),
        (places, 'bookmark-missing'),
        (places, 'gnome-fs-bookmark-missing'),
        (places, 'stock_delete-bookmark')
    ]
}

folder_download_group = {
    'group_name': 'Folder-likes - Downloads',
    'copies': [
        (places, 'folder-download-open'),
        (places, 'folder-downloads'),
        (places, 'folder-download'),
    ]
}

folder_pictures_group = {
    'group_name': 'Folder-likes - Pictures',
    'copies': [
        (places, 'folder-pictures'),
        (places, 'folder_pictures'),
        (places, 'folder-picture'),
        (places, 'user-images'),
        (places, 'user-pictures'),
        (places, 'folder-pictures-open'),
    ]
}

folder_music_group = {
    'group_name': 'Folder-likes - Music',
    'copies': [
        (places, 'folder-music'),
        (places, 'folder-music-open'),
        (places, 'library-music'),
        (places, 'folder-sound')
    ]
}

folder_remote_group = {
    'group_name': 'Folder-likes - Remote',
    'copies': [
        (places, 'folder-remote-apf'),
        (places, 'folder-remote-ftp'),
        (places, 'folder-remote-nfs'),
        (places, 'folder-remote-smb'),
        (places, 'folder-remote-ssh'),
        (places, 'folder-remote'),
        (places, 'knetattach'),
    ]
}

network_manager_group = {
    'group_name': 'Folder-likes - Network',
    'copies': [
        (places, 'network-manager'),
        (places, 'folder-network'),
        (places, 'network_local'),
        (places, 'network-server'),
        (places, 'network'),
        (places, 'network-workgroup'),
        (places, 'repository'),
    ]
}

user_desktop_group = {
    'group_name': 'Folder-likes - Desktop',
    'copies': [
        (places, 'user-desktop'),
        (places, 'desktop'),
        (places, 'gnome-ccdesktop'),
        (places, 'gnome-desktop-config'),
        (places, 'gnome-desktop'),
        (places, 'gnome-fs-desktop'),
    ]
}

folder_open_group = {
    'group_name': 'Folder-likes - Open',
    'copies': [
        (places, 'folder-open'),
        (places, 'folder_open'),
        (places, 'folder-music-open'),
        (places, 'folder-download-open'),
        (places, 'folder-pictures-open'),
        (places, 'folder-publicshare-open'),
        (places, 'folder-templates-open'),
        (places, 'gnome-fs-directory-open'),
        (places, 'stock_open'),
        (places, 'user-home-open'),
    ]
}

folder_image_group = {
    'group_name': 'Folder-likes - Image',
    'copies': [
        (places, 'folder-image'),
        (places, 'folder-images')
    ]
}

folder_drive_group = {
    'group_name': 'Folder-likes - Drive',
    'copies': [
        (places, 'folder-gdrive'),
        (places, 'folder-google-drive'),
        (places, 'insync-folder')
    ]
}

folder_uniques_group = {
    'group_name': 'Folder-likes - Uniques',
    'copies': [
        (places, 'folder-activities'),
        (places, 'folder-add'),
        (places, 'folder-android'),
        (places, 'folder-applications'),
        (places, 'folder-arduino'),
        (places, 'folder-books'),
        (places, 'folder-cd'),
        (places, 'folder-development'),
        (places, 'folder-dropbox'),
        (places, 'folder-yandex-disk'),
        (places, 'folder-drag-accept.svg'),
        (places, 'folder-steam'),
        (places, 'folder-git'),
        (places, 'folder-gitlab'),
        (places, 'folder-github'),
        (places, 'folder-gnome'),
        (places, 'folder-go'),
        (places, 'folder-important'),
        (places, 'folder-java'),
        (places, 'folder-kde'),
        (places, 'folder-linux'),
        (places, 'folder-mail'),
        (places, 'folder-nextcloud'),
        (places, 'folder-print'),
        (places, 'folder-private'),
        (places, 'folder-projects'),
        (places, 'folder-root'),
        (places, 'folder-snap'),
        (places, 'folder-system'),
        (places, 'folder-tar'),
        (places, 'folder-backup'),
        (places, 'folder-wine'),
        (places, 'folder-3dprint'),
        (places, 'folder-pcloud'),
        (places, 'folder-copy-cloud'),
        (places, 'folder-nextcloud'),
        (places, 'folder-owncloud'),
        (places, 'folder-sync'),
        (places, 'folder-syncthing'),
        (places, 'folder-torrent'),
        (places, 'folder-vbox')
    ]
}

folder_videos_group = {
    'group_name': 'Folder-likes - Videos',
    'copies': [
        (places, 'folder-videos'),
        (places, 'folder-video-alt'),
        (places, 'folder-video')
    ]
}

folder_templates_group = {
    'group_name': 'Folder-likes - Templates',
    'copies': [
        (places, 'folder-templates'),
        (places, 'folder-templates-open')
    ]
}

folder_recent_group = {
    'group_name': 'Folder-likes - Recent',
    'copies': [
        (places, 'folder-recent'),
        (places, 'folder-temp')
    ]
}

folder_cloud_group = {
    'group_name': 'Folder-likes - Cloud',
    'copies': [
        (places, 'folder-cloud'),
        (places, 'folder-CloudStation'),
        (places, 'folder-mail-cloud'),
        (places, 'folder-meocloud'),
        (places, 'folder-synology')
    ]
}

folder_documents_group = {
    'group_name': 'Folder-likes - Documents',
    'copies': [
        (places, 'folder-documents'),
        (places, 'folder_man'),
        (places, 'folder_wordprocessing'),
    ]
}

folder_image_people_group = {
    'group_name': 'Folder-likes - Image People',
    'copies': [
        (places, 'folder-image-people'),
        (places, 'folder_home2'),
    ]
}

folder_megasync_group = {
    'group_name': 'Folder-likes - Mega',
    'copies': [
        (places, 'folder-megasync'),
        (places, 'folder-mega'),
    ]
}

folder_public_group = {
    'group_name': 'Folder-likes - Public',
    'copies': [
        (places, 'folder-publicshare'),
        (places, 'folder-public'),
        (places, 'folder-publicshare-open'),
    ]
}

folder_share_group = {
    'group_name': 'Folder-likes - Share',
    'copies': [
        (places, 'gnome-mime-x-directory-share'),
        (places, 'gnome-mime-x-directory-smb-share'),
        (places, 'gnome-mime-x-directory-smb-workgroup'),
        (places, 'gnome-fs-network'),
        (places, 'gnome-network'),
        (places, 'gtk-network'),
        (places, 'network-server-database'),
        (places, 'redhat-system-group'),
        (places, 'stock_shared-by-me'),
        (places, 'stock_shared-to-me'),
        (places, 'user-share'),
        (places, 'neat'),
    ]
}

folder_saved_search_group = {
    'group_name': 'Folder-likes - Saved Search',
    'copies': [
        (places, 'folder-saved-search'),
        (places, 'application-x-gnome-saved-search'),
    ]
}

folder_text_group = {
    'group_name': 'Folder-likes - Text',
    'copies': [
        (places, 'folder-text'),
        (places, 'folder-txt'),
    ]
}

folder_unlocked_group = {
    'group_name': 'Folder-likes - Unlocked',
    'copies': [
        (places, 'folder-unlocked'),
        (places, 'folder-decrypted'),
    ]
}

folder_visiting_group = {
    'group_name': 'Folder-likes - Visiting',
    'copies': [
        (places, 'folder-visiting'),
        (places, 'gnome-fs-directory-visiting'),
    ]
}

# --- outros --------------------------------------------------------------------------------------
trash_group = {
    'group_name': 'Trash',
    'copies': [
        (places, 'edittrash'),
        (places, 'emptytrash'),
        (places, 'gnome-fs-trash-empty-accept'),
        (places, 'gnome-fs-trash-empty'),
        (places, 'gnome-fs-trash-full'),
        (places, 'gnome-stock-trash-full'),
        (places, 'gnome-stock-trash'),
        (places, 'stock_trash_full'),
        (places, 'trashcan_empty'),
        (places, 'trashcan_full-new'),
        (places, 'trashcan_full'),
        (places, 'user-trash-full'),
        (places, 'user-trash'),
        (places, 'xfce-trash_empty'),
        (places, 'xfce-trash-full'),
        (places, 'xfce-trash_full'),
        (apps, 'trashindicator')
    ]
}

mail_group = {
    'group_name': 'Mail',
    'copies': [
        (places, 'mail-outbox'),
        (places, 'mail-mailbox'),
        (places, 'mail-inbox'),
        (apps, 'google-inbox'),
        (apps, 'mailspring'),
        (apps, 'mutt'),
        (apps, 'kontact-import-wizard'),
        (apps, 'bluemail'),
        (apps, 'claws-mail-128x128'),
        (apps, 'claws-mail-32x32'),
        (apps, 'claws-mail-64x64'),
        (apps, 'claws-mail'),
        (apps, 'e-mail'),
        (apps, 'clawsker'),
        (apps, 'kube-mail'),
        (apps, 'xfce-newmail'),
        (apps, 'unity-mail'),
        (apps, 'yast-mail'),
        (apps, 'email-client'),
        (apps, 'email'),
        (apps, 'x-office-mail'),
        (apps, 'xfce-mail'),
        (apps, 'io.elementary.mail'),
        (apps, 'unity-webapps-mail-ru'),
        (apps, 'ximian-evolution-email'),
        (apps, 'internet-mail'),
        (apps, 'deepin-mail'),
        (apps, 'kmailcvt'),
        (apps, 'org.kde.merkuro.mail'),
        (apps, 'org.xfce.mailreader'),
        (apps, 'xfmail'),
        (apps, 'redhat-email'),
        (apps, 'mail-client'),
        (apps, 'mail-generic'),
        (apps, 'mail-notification'),
        (apps, 'mail'),
        (apps, 'mailnag'),
        (apps, 'mailru-mail.ru'),
        (apps, 'mail_generic'),
        (apps, 'package_internet_email'),
        (apps, 'kmail'),
        (apps, 'kmail2'),
        (apps, 'evolution-mail'),
        (apps, 'preferences-mail'),
        (apps, 'internet_mail'),
        (apps, 'org.claws_mail.Claws-Mail'),
    ]
}

has_text_mimetypes_group = {
    'group_name': 'Has text - mimetypes',
    'copies': [
        (mimetypes, 'android-package-archive'),
        (mimetypes, 'application-7zip'),
        (mimetypes, 'application-afdesigner'),
        (mimetypes, 'application-archive'),
        (mimetypes, 'application-archive-zip'),
        (mimetypes, 'application-ascii'),
        (mimetypes, 'application-audio-playlist'),
        (mimetypes, 'application-audio'),
        (mimetypes, 'application-certificate'),
        (mimetypes, 'application-database'),
        (mimetypes, 'application-drawing-template'),
        (mimetypes, 'application-epub+zip'),
        (mimetypes, 'application-executable'),
        (mimetypes, 'application-flash'),
        (mimetypes, 'application-font'),
        (mimetypes, 'application-illustrator'),
        (mimetypes, 'application-image-avif'),
        (mimetypes, 'application-image-bmp'),
        (mimetypes, 'application-image-exr'),
        (mimetypes, 'application-image-gif'),
        (mimetypes, 'application-image-ico'),
        (mimetypes, 'application-image-jpg'),
        (mimetypes, 'application-image-jxl'),
        (mimetypes, 'application-image-png'),
        (mimetypes, 'application-image-psd'),
        (mimetypes, 'application-image-tga'),
        (mimetypes, 'application-image-tiff'),
        (mimetypes, 'application-info'),
        (mimetypes, 'application-javascript'),
        (mimetypes, 'application-java'),
        (mimetypes, 'application-json'),
        (mimetypes, 'application-mathematica'),
        (mimetypes, 'application-mbox'),
        (mimetypes, 'application-msword-template'),
        (mimetypes, 'application-pdf'),
        (mimetypes, 'application-postscript'),
        (mimetypes, 'application-presentation'),
        (mimetypes, 'application-presentation-template'),
        (mimetypes, 'application-rss'),
        (mimetypes, 'application-rtf'),
        (mimetypes, 'application-software'),
        (mimetypes, 'application-table'),
        (mimetypes, 'application-table-template'),
        (mimetypes, 'application-toml'),
        (mimetypes, 'application-torrent'),
        (mimetypes, 'application-vector'),
        (mimetypes, 'application-video'),
        (mimetypes, 'application-vnd.appimage'),
        (mimetypes, 'application-vnd.comicbook+zip'),
        (mimetypes, 'application-vnd.google-earth.kml'),
        (mimetypes, 'application-vnd.ms-access'),
        (mimetypes, 'application-vnd.ms-powerpoint'),
        (mimetypes, 'application-vnd.nokia.xml.qt.resource'),
        (mimetypes, 'application-vnd.oasis.opendocument.chart'),
        (mimetypes, 'application-vnd.oasis.opendocument.chart-template'),
        (mimetypes, 'application-vnd.oasis.opendocument.database'),
        (mimetypes, 'application-vnd.oasis.opendocument.formula'),
        (mimetypes, 'application-vnd.oasis.opendocument.formula-template'),
        (mimetypes, 'application-vnd.oasis.opendocument.image'),
        (mimetypes, 'application-vnd.oasis.opendocument.image-template'),
        (mimetypes, 'application-vnd.oasis.opendocument.presentation'),
        (mimetypes, 'application-vnd.oasis.opendocument.spreadsheet'),
        (mimetypes, 'application-vnd.scribus'),
        (mimetypes, 'application-web-template'),
        (mimetypes, 'application-word'),
        (mimetypes, 'application-x-ace'),
        (mimetypes, 'application-x-arj'),
        (mimetypes, 'application-x-asp'),
        (mimetypes, 'application-x-blender'),
        (mimetypes, 'application-x-bzdvi'),
        (mimetypes, 'application-x-bzip'),
        (mimetypes, 'application-x-cbr'),
        (mimetypes, 'application-x-cd-image'),
        (mimetypes, 'application-x-chm'),
        (mimetypes, 'application-x-compressed-tar'),
        (mimetypes, 'application-x-cpio'),
        (mimetypes, 'application-x-deb-debian'),
        (mimetypes, 'application-x-deb-linuxmint'),
        (mimetypes, 'application-x-deb-ubuntu'),
        (mimetypes, 'application-x-desktop-budgie'),
        (mimetypes, 'application-x-desktop-gnome'),
        (mimetypes, 'application-x-desktop-kde'),
        (mimetypes, 'application-x-desktop-linuxmint'),
        (mimetypes, 'application-x-desktop-lxde'),
        (mimetypes, 'application-x-desktop-unity'),
        (mimetypes, 'application-x-desktop-xfce'),
        (mimetypes, 'application-x-gameboy-color-rom'),
        (mimetypes, 'application-x-glade'),
        (mimetypes, 'application-x-gzdvi'),
        (mimetypes, 'application-x-gzip'),
        (mimetypes, 'application-x-ipynb+json'),
        (mimetypes, 'application-x-jsx'),
        (mimetypes, 'application-x-keepassx'),
        (mimetypes, 'application-x-kexiproject-shortcut'),
        (mimetypes, 'application-x-kmymoney'),
        (mimetypes, 'application-x-krita'),
        (mimetypes, 'application-x-lha'),
        (mimetypes, 'application-x-love-game'),
        (mimetypes, 'application-x-lyx'),
        (mimetypes, 'application-x-lzma'),
        (mimetypes, 'application-x-lzop'),
        (mimetypes, 'application-x-mono-develop'),
        (mimetypes, 'application-x-ms-dos-executable'),
        (mimetypes, 'application-x-msi'),
        (mimetypes, 'application-x-ms-shortcut'),
        (mimetypes, 'application-x-osm+xml'),
        (mimetypes, 'application-x-partial-download'),
        (mimetypes, 'application-x-perl'),
        (mimetypes, 'application-x-php'),
        (mimetypes, 'application-xps'),
        (mimetypes, 'application-x-rar'),
        (mimetypes, 'application-x-revelation'),
        (mimetypes, 'application-x-rpm-fedora'),
        (mimetypes, 'application-x-rpm-opensuse'),
        (mimetypes, 'application-x-rpm-redhat'),
        (mimetypes, 'application-x-ruby'),
        (mimetypes, 'application-x-scribus'),
        (mimetypes, 'application-x-smb-server'),
        (mimetypes, 'application-x-smb-workgroup'),
        (mimetypes, 'application-x-solus-package'),
        (mimetypes, 'application-x-sqlite'),
        (mimetypes, 'application-x-stuffit'),
        (mimetypes, 'application-x-subrip'),
        (mimetypes, 'application-x-tar'),
        (mimetypes, 'application-x-tarz'),
        (mimetypes, 'application-x-tha'),
        (mimetypes, 'application-x-theme'),
        (mimetypes, 'application-x-thz'),
        (mimetypes, 'application-x-trash'),
        (mimetypes, 'application-x-tsx'),
        (mimetypes, 'application-x-tzo'),
        (mimetypes, 'application-x-virtualbox-vbox'),
        (mimetypes, 'application-x-virtualbox-vdi'),
        (mimetypes, 'application-x-wii-rom'),
        (mimetypes, 'application-x-wii-wad'),
        (mimetypes, 'application-x-wine-extension-ini'),
        (mimetypes, 'application-yaml'),
        (mimetypes, 'audio-flac'),
        (mimetypes, 'audio-midi'),
        (mimetypes, 'audio-mp3'),
        (mimetypes, 'audio-wav'),
        (mimetypes, 'audio-x-smart-playlist'),
        (mimetypes, 'encrypted'),
        (mimetypes, 'gnome-mime-application-magicpoint'),
        (mimetypes, 'gnome-mime-text-x-makefile'),
        (mimetypes, 'image-vnd.dwg'),
        (mimetypes, 'image-x-xcf'),
        (mimetypes, 'radio'),
        (mimetypes, 'stock_addressbook'),
        (mimetypes, 'text-calendar'),
        (mimetypes, 'text-css_orig'),
        (mimetypes, 'text-css'),
        (mimetypes, 'text-html'),
        (mimetypes, 'text-less'),
        (mimetypes, 'text-markdown'),
        (mimetypes, 'text-rust'),
        (mimetypes, 'text-vnd.wap.wmlscript'),
        (mimetypes, 'text-wiki'),
        (mimetypes, 'text-x-adasrc'),
        (mimetypes, 'text-x-arduino'),
        (mimetypes, 'text-x-changelog'),
        (mimetypes, 'text-x-c++hdr'),
        (mimetypes, 'text-x-chdr'),
        (mimetypes, 'text-x-copying'),
        (mimetypes, 'text-x-cpp'),
        (mimetypes, 'text-x-csharp'),
        (mimetypes, 'text-x-c++'),
        (mimetypes, 'text-x-c'),
        (mimetypes, 'text-x-dsrc'),
        (mimetypes, 'text-x-fortran'),
        (mimetypes, 'text-x-gettext-translation'),
        (mimetypes, 'text-x-go'),
        (mimetypes, 'text-x-gtkrc'),
        (mimetypes, 'text-x-install'),
        (mimetypes, 'text-x-kotlin'),
        (mimetypes, 'text-x-matlab'),
        (mimetypes, 'text-xml'),
        (mimetypes, 'text-x-octave'),
        (mimetypes, 'text-x-pascal'),
        (mimetypes, 'text-x-readme'),
        (mimetypes, 'text-x-rpm-spec'),
        (mimetypes, 'text-x-ruby'),
        (mimetypes, 'text-x-sass'),
        (mimetypes, 'text-x-scala'),
        (mimetypes, 'text-x-script'),
        (mimetypes, 'text-x-tcl'),
        (mimetypes, 'text-x-texmacs'),
        (mimetypes, 'text-x-tex'),
        (mimetypes, 'text-x-typescript'),
        (mimetypes, 'text-x-vala'),
        (mimetypes, 'text-x-wxmathml'),
        (mimetypes, 'unknown'),
        (mimetypes, 'x-media-podcast'),
        (mimetypes, 'xoj'),
        (mimetypes, 'xopt'),
    ]
}

has_text_apps_group = {
    'group_name': 'Has text - Apps',
    'copies': [
        (apps, '0cc-famitracker'),
        (apps, '1cestart'),
        (apps, '2048-qt'),
        (apps, '2048'),
        (apps, '4diac-ide'),
        (apps, '4digits'),
        (apps, '4Pane'),
        (apps, '6180-the-moon'),
        (apps, '7kaa'),
        (apps, 'accessories-calculator'),
        (apps, 'accessories-dictionary'),
        (apps, 'acreloaded'),
        (apps, 'activitywatch'),
        (apps, 'ADLplug'),
        (apps, 'AdobeIllustrator'),
        (apps, 'AdobePhotoshop'),
        (apps, 'agentdesktop'),
        (apps, 'agent'),
        (apps, 'airtame-application'),
        (apps, 'amarok_change_language'),
        (apps, 'amazonmp3'),
        (apps, 'amazon-store'),
        (apps, 'angular-console'),
        (apps, 'apktool'),
        (apps, 'appcode'),
        (apps, 'appimagekit-diffuse'),
        (apps, 'appimagekit-paymo-widget'),
        (apps, 'applications-education-mathematics'),
        (apps, 'applications-haskell'),
        (apps, 'applications-php'),
        (apps, 'applixware'),
        (apps, 'aqemu'),
        (apps, 'arcolinux-hello'),
        (apps, 'arduino'),
        (apps, 'artikulate'),
        (apps, 'aspia_client'),
        (apps, 'aspia_console'),
        (apps, 'astah_community'),
        (apps, 'astah_gsn'),
        (apps, 'astah_professional'),
        (apps, 'astah_sysml'),
        (apps, 'astah_uml'),
        (apps, 'astah_viewer'),
        (apps, 'atlauncher'),
        (apps, 'autokey'),
        (apps, 'avimetaedit'),
        (apps, 'avogadro-icon'),
        (apps, 'awesomebump'),
        (apps, 'azardi'),
        (apps, 'bashtop'),
        (apps, 'bbc'),
        (apps, 'billard-gl'),
        (apps, 'birdfont'),
        (apps, 'bitcoin'),
        (apps, 'bitmap2component'),
        (apps, 'bless'),
        (apps, 'bluemail'),
        (apps, 'brackets'),
        (apps, 'br.com.jeanhertel.adriconf'),
        (apps, 'briss-icon'),
        (apps, 'btrfs-assistant'),
        (apps, 'byobu'),
        (apps, 'cacher'),
        (apps, 'calendar'),
        (apps, 'calligraplanwork'),
        (apps, 'cantor'),
        (apps, 'caption'),
        (apps, 'cemu'),
        (apps, 'chmsee-icon'),
        (apps, 'chrome-fljalecfjciodhpcledpamjachpmelml-Default'),
        (apps, 'chromium-dev'),
        (apps, 'cine-encoder'),
        (apps, 'Civ-V'),
        (apps, 'clawsker'),
        (apps, 'clion'),
        (apps, 'colon'),
        (apps, 'com.bitstower.Markets'),
        (apps, 'com.dhsdevelopments.Climaxima'),
        (apps, 'com.github.aimproxy.dotfonts'),
        (apps, 'com.github.artemanufrij.hashit'),
        (apps, 'com.github.artemanufrij.regextester'),
        (apps, 'com.github.artemanufrij.webpin'),
        (apps, 'com.github.bartzaalberg.alias'),
        (apps, 'com.github.bartzaalberg.bookmark-manager'),
        (apps, 'com.github.bartzaalberg.php-tester'),
        (apps, 'com.github.bartzaalberg.vala-tester'),
        (apps, 'com.github.basjam.valacompiler'),
        (apps, 'com.github.cassidyjames.clairvoyant'),
        (apps, 'com.github.cassidyjames.principles'),
        (apps, 'com.github.cjfloss.envelope'),
        (apps, 'com.github.coralynnmay.goodvibesapp'),
        (apps, 'com.github.eudaldgr.elements'),
        (apps, 'com.github.fushinari.Wordbook'),
        (apps, 'com.github.gi_lom.dialect'),
        (apps, 'com.github.hugolabe.Wike'),
        (apps, 'com.github.huluti.Coulr'),
        (apps, 'com.github.huluti.ImCompressor'),
        (apps, 'com.github.jeremyvaartjes.comgen'),
        (apps, 'com.github.johnfactotum.QuickLookup'),
        (apps, 'com.github.kjlaw89.archetype'),
        (apps, 'com.github.mdh34.quickdocs'),
        (apps, 'com.github.muriloventuroso.easyssh'),
        (apps, 'com.github.padjis.ghistory'),
        (apps, 'com.github.plugarut.pwned-checker'),
        (apps, 'com.github.ranfdev.raddiu'),
        (apps, 'com.github.ryonakano.konbucase'),
        (apps, 'com.github.subhadeepjasu.pebbles'),
        (apps, 'com.github.thejambi.psnotes'),
        (apps, 'com.github.timecraft.js-test'),
        (apps, 'com.github.zren.kdeconnectdevice'),
        (apps, 'com.gitlab.zehkira.Myuzi'),
        (apps, 'com.rafaelmardojai.WebfontKitGenerator'),
        (apps, 'cudatext-512'),
        (apps, 'cura-icon'),
        (apps, 'cutemarked'),
        (apps, 'cvpcb'),
        (apps, 'cz.pervoj.valdo-gtk'),
        (apps, 'datagrip'),
        (apps, 'dataspell'),
        (apps, 'dconf-editor'),
        (apps, 'de_logo_48px'),
        (apps, 'denemo'),
        (apps, 'deskreen'),
        (apps, 'desktop-environment-tde'),
        (apps, 'dev.boxi.Boxi'),
        (apps, 'dev.geopjr.Collision'),
        (apps, 'dev.geopjr.Hashbrown'),
        (apps, 'devhelp'),
        (apps, 'dev.mufeed.Wordbook'),
        (apps, 'dev.vlinkz.NixosConfEditor'),
        (apps, 'dianara'),
        (apps, 'digitallyimported'),
        (apps, 'distributor-logo-absolute'),
        (apps, 'distributor-logo-academix'),
        (apps, 'distributor-logo-aix'),
        (apps, 'distributor-logo-archbang'),
        (apps, 'distributor-logo-ms-dos'),
        (apps, 'distributor-logo-pop-os'),
        (apps, 'distributor-logo-simply'),
        (apps, 'distributor-logo-ultimate-edition'),
        (apps, 'distributor-logo-zorin'),
        (apps, 'dmanager'),
        (apps, 'dmd-doc'),
        (apps, 'dosbox-ece'),
        (apps, 'dosbox-staging'),
        (apps, 'dosbox'),
        (apps, 'dosbox-x'),
        (apps, 'dotcover'),
        (apps, 'dotmemory'),
        (apps, 'dotpeek'),
        (apps, 'dottrace'),
        (apps, 'double-action-boogaloo'),
        (apps, 'eiciel'),
        (apps, 'emulationstation'),
        (apps, 'enhanced_browsing'),
        (apps, 'ente'),
        (apps, 'epic-games'),
        (apps, 'eqonomize'),
        (apps, 'eu.scarpetta.QtWAW'),
        (apps, 'extraterm'),
        (apps, 'facebook'),
        (apps, 'famitracker'),
        (apps, 'fcitx-sogoupinyin'),
        (apps, 'feedback'),
        (apps, 'filebot'),
        (apps, 'filezilla'),
        (apps, 'filmulator-gui'),
        (apps, 'FlashCS6'),
        (apps, 'fokus'),
        (apps, 'fontforge'),
        (apps, 'fontypython'),
        (apps, 'foursquare'),
        (apps, 'freecad'),
        (apps, 'freeciv-manual'),
        (apps, 'freeciv-server'),
        (apps, 'freedroid'),
        (apps, 'freeoffice-planmaker'),
        (apps, 'freeoffice-presentations'),
        (apps, 'freeoffice-textmaker'),
        (apps, 'FreeTexturePacker'),
        (apps, 'fritzing'),
        (apps, 'fs-uae-launcher'),
        (apps, 'ftb-app'),
        (apps, 'fuse'),
        (apps, 'gimagereader'),
        (apps, 'gisto'),
        (apps, 'gksu-root-terminal'),
        (apps, 'glyphr-studio-desktop'),
        (apps, 'gnome-characters'),
        (apps, 'gnome-mahjongg'),
        (apps, 'gnome-sudoku'),
        (apps, 'gnome-tetravex'),
        (apps, 'goland'),
        (apps, 'google-agenda'),
        (apps, 'google-chrome-beta'),
        (apps, 'google-chrome-dev'),
        (apps, 'google-earth-pro'),
        (apps, 'google-hangouts'),
        (apps, 'googleplus'),
        (apps, 'google-translate'),
        (apps, 'goterminal'),
        (apps, 'GP6-icon'),
        (apps, 'gqrx'),
        (apps, 'grafx2'),
        (apps, 'grub-customizer'),
        (apps, 'gsharp'),
        (apps, 'gtranslator'),
        (apps, 'guitarix'),
        (apps, 'gummi'),
        (apps, 'gzdoom'),
        (apps, 'haroopad'),
        (apps, 'hashit'),
        (apps, 'hatari'),
        (apps, 'hex-editor'),
        (apps, 'hivelytracker'),
        (apps, 'hp_logo'),
        (apps, 'hydrogen'),
        (apps, 'hyper'),
        (apps, 'ice'),
        (apps, 'imhex'),
        (apps, 'in.bharatkalluri.shortcircuit'),
        (apps, 'insomnia-designer'),
        (apps, 'intellij'),
        (apps, 'intel'),
        (apps, 'io.elementary.code'),
        (apps, 'io.github.ImEditor'),
        (apps, 'io.github.OpenToonz'),
        (apps, 'ipython'),
        (apps, 'ipython3'),
        (apps, 'jadx'),
        (apps, 'jblue'),
        (apps, 'jetbrains-toolbox'),
        (apps, 'JForex'),
        (apps, 'jgray'),
        (apps, 'jgreen'),
        (apps, 'joplin'),
        (apps, 'jpexs-decompiler'),
        (apps, 'JRomManager'),
        (apps, 'KakaoTalk'),
        (apps, 'kakoune'),
        (apps, 'kalgebra'),
        (apps, 'kanagram'),
        (apps, 'kanatest'),
        (apps, 'kbibtex'),
        (apps, 'kblackbox'),
        (apps, 'kde-frameworks'),
        (apps, 'kdevelop'),
        (apps, 'kega-fusion'),
        (apps, 'keurocalc'),
        (apps, 'khotkeys'),
        (apps, 'kicad'),
        (apps, 'kid3'),
        (apps, 'kile'),
        (apps, 'kimagemapeditor'),
        (apps, 'klatexformula'),
        (apps, 'klavaro'),
        (apps, 'klayout'),
        (apps, 'kmymoney'),
        (apps, 'koodo-reader'),
        (apps, 'korgac'),
        (apps, 'krename'),
        (apps, 'kronometer'),
        (apps, 'kshisen'),
        (apps, 'ksudoku'),
        (apps, 'ktip'),
        (apps, 'kvantum'),
        (apps, 'kvirc'),
        (apps, 'kwalletmanager'),
        (apps, 'kwave'),
        (apps, 'kwordquiz'),
        (apps, 'l3afpad'),
        (apps, 'LanguageTool'),
        (apps, 'lastfm'),
        (apps, 'latte-dock'),
        (apps, 'leonflix'),
        (apps, 'lftp'),
        (apps, 'libreoffice-math'),
        (apps, 'lsp-plugins'),
        (apps, 'lzdoom'),
        (apps, 'mame'),
        (apps, 'manjaro-architect'),
        (apps, 'marknoto'),
        (apps, 'markpado'),
        (apps, 'mate-inhibit-applet'),
        (apps, 'maxima'),
        (apps, 'maxthon-browser'),
        (apps, 'mednaffe'),
        (apps, 'megabasterd'),
        (apps, 'mega'),
        (apps, 'mendeley-desktop'),
        (apps, 'mhwaveedit'),
        (apps, 'microsoft-edge-beta'),
        (apps, 'microsoft-edge-dev'),
        (apps, 'micro'),
        (apps, 'miktex-console'),
        (apps, 'mikutter'),
        (apps, 'milkytracker'),
        (apps, 'minetime'),
        (apps, 'minicraft+'),
        (apps, 'mintsources-foreign'),
        (apps, 'mlterm'),
        (apps, 'modelsim'),
        (apps, 'moderndeck'),
        (apps, 'molotov'),
        (apps, 'monodoc'),
        (apps, 'MotionBox'),
        (apps, 'motrix'),
        (apps, 'movmetaedit'),
        (apps, 'mozc'),
        (apps, 'ms-excel'),
        (apps, 'ms-onenote'),
        (apps, 'ms-outlook'),
        (apps, 'ms-powerpoint'),
        (apps, 'ms-word'),
        (apps, 'mtvmusic'),
        (apps, 'mullvad-browser'),
        (apps, 'muon'),
        (apps, 'mupen64plus-qt'),
        (apps, 'muse-dash'),
        (apps, 'museeks'),
        (apps, 'museeq'),
        (apps, 'musescore'),
        (apps, 'musikcube'),
        (apps, 'mutt'),
        (apps, 'mx-qsi'),
        (apps, 'nbteditor'),
        (apps, 'ndm'),
        (apps, 'neovim'),
        (apps, 'net.christianbeier.Gromit-MPX'),
        (apps, 'netradiant'),
        (apps, 'nicotine-plus'),
        (apps, 'nishang'),
        (apps, 'nitroshare'),
        (apps, 'nnn'),
        (apps, 'NoMachine-icon'),
        (apps, 'notable'),
        (apps, 'notepadqq'),
        (apps, 'notion'),
        (apps, 'nsm-legacy-gui'),
        (apps, 'nsm-proxy'),
        (apps, 'nutty'),
        (apps, 'nvtop'),
        (apps, 'nym-vpn-app'),
        (apps, 'ocrfeeder'),
        (apps, 'ooo-math'),
        (apps, 'openbve'),
        (apps, 'openttd'),
        (apps, 'ophcrack'),
        (apps, 'OPNplug'),
        (apps, 'org.es_de.emulationstation-de'),
        (apps, 'org.eu.encom.matrique'),
        (apps, 'org.gabmus.mdwriter'),
        (apps, 'org.gabmus.notorious'),
        (apps, 'org.gnome.Crosswords'),
        (apps, 'org.gnome.design.Lorem'),
        (apps, 'org.gnome.design.Typography'),
        (apps, 'org.gnome.FontManager'),
        (apps, 'org.gnome.FontViewer'),
        (apps, 'org.gnome.Gtranslator'),
        (apps, 'org.gnome.Tau'),
        (apps, 'org.gnome.World.Citations'),
        (apps, 'org.gustavoperedo.FontDownloader'),
        (apps, 'org.kde.activeWindowControl'),
        (apps, 'org.kde.kontrast'),
        (apps, 'org.kde.plasma.appmenu'),
        (apps, 'org.kde.plasma.calendar.wl'),
        (apps, 'org.kde.plasma.digitalclock-ng'),
        (apps, 'org.kde.plasma.digitalclock'),
        (apps, 'org.kde.plasma.digitalclock.wl'),
        (apps, 'org.kde.plasma.fuzzyclock'),
        (apps, 'org.kde.plasma.keyboardlayout'),
        (apps, 'org.kde.plasma.simplemenu'),
        (apps, 'org.kde.windowappmenu'),
        (apps, 'org.kde.windowtitle'),
        (apps, 'org.wezfurlong.wezterm'),
        (apps, 'osu'),
        (apps, 'pcloud'),
        (apps, 'PCSX2'),
        (apps, 'pdfarranger'),
        (apps, 'pdfchain'),
        (apps, 'pdfshuffler'),
        (apps, 'pdfstudio'),
        (apps, 'phd2'),
        (apps, 'phpstorm'),
        (apps, 'pixeluvo'),
        (apps, 'planner'),
        (apps, 'planwork'),
        (apps, 'poedit'),
        (apps, 'pokete'),
        (apps, 'polari'),
        (apps, 'polo'),
        (apps, 'portal2'),
        (apps, 'powersploit'),
        (apps, 'pppoeconf'),
        (apps, 'preferences-desktop-font'),
        (apps, 'preferences-desktop-locale'),
        (apps, 'preferences-kcalc-constants'),
        (apps, 'preferences-system-notifications-rtl'),
        (apps, 'preferences-web-browser-stylesheets'),
        (apps, 'prepos'),
        (apps, 'pritunl_client_electron'),
        (apps, 'projectM'),
        (apps, 'pronterface'),
        (apps, 'ptyxis'),
        (apps, 'punes'),
        (apps, 'pureref'),
        (apps, 'pycharmedu'),
        (apps, 'pycharm'),
        (apps, 'Q4Wine'),
        (apps, 'qalculate'),
        (apps, 'qbittorrent'),
        (apps, 'qcalcfilehash'),
        (apps, 'qctools'),
        (apps, 'qnapi'),
        (apps, 'qtassistant'),
        (apps, 'qtdbusviewer'),
        (apps, 'qtdesigner'),
        (apps, 'qtlinguist'),
        (apps, 'qtodotxt'),
        (apps, 'qt'),
        (apps, 'qtwebflix'),
        (apps, 'quadrapassel'),
        (apps, 'quassel'),
        (apps, 'qubic'),
        (apps, 'quickaccess'),
        (apps, 'quickhash'),
        (apps, 'qutebrowser'),
        (apps, 'radiotunes'),
        (apps, 'rare'),
        (apps, 'rclonetray'),
        (apps, 'recstudio'),
        (apps, 'remarkable'),
        (apps, 'remmina'),
        (apps, 'renoise'),
        (apps, 'resharper-c++'),
        (apps, 'resharper'),
        (apps, 'revolt-desktop'),
        (apps, 'rider'),
        (apps, 'riot-web'),
        (apps, 'rstudio'),
        (apps, 'rubymine'),
        (apps, 'ru.exlmoto.bezierclock'),
        (apps, 'satisfactory'),
        (apps, 'scantailor'),
        (apps, 'scid'),
        (apps, 'scilab'),
        (apps, 'securecrt'),
        (apps, 'sftpclient'),
        (apps, 'shadow-beta'),
        (apps, 'shadow-dev'),
        (apps, 'shadps4'),
        (apps, 'shellnoob'),
        (apps, 'sidekick-browser'),
        (apps, 'sigil'),
        (apps, 'simsu'),
        (apps, 'skype-call-recorder'),
        (apps, 'skype'),
        (apps, 'smartsim'),
        (apps, 'soapui'),
        (apps, 'somafm'),
        (apps, 'sonic-pi'),
        (apps, 'sr-editor'),
        (apps, 'statalogo_14'),
        (apps, 'stretchly'),
        (apps, 'suanPan'),
        (apps, 'sublime-merge'),
        (apps, 'sublime'),
        (apps, 'substance'),
        (apps, 'subtitlecomposer'),
        (apps, 'sudoku'),
        (apps, 'svgcleaner-gui'),
        (apps, 'synapse'),
        (apps, 'system76-driver'),
        (apps, 'tanglet'),
        (apps, 'teams-for-linux'),
        (apps, 'tekken-7'),
        (apps, 'terminal'),
        (apps, 'terminator'),
        (apps, 'terminix'),
        (apps, 'terminology'),
        (apps, 'terminus'),
        (apps, 'termius-app'),
        (apps, 'terratech'),
        (apps, 'tetrio-desktop'),
        (apps, 'texmaker'),
        (apps, 'texstudio'),
        (apps, 'textadept'),
        (apps, 'thonny'),
        (apps, 'thorium'),
        (apps, 'tidal'),
        (apps, 'tiktok'),
        (apps, 'tiled'),
        (apps, 'tilesetter'),
        (apps, 'timidity'),
        (apps, 'tipp10'),
        (apps, 'tixati'),
        (apps, 'tlauncher'),
        (apps, 'tokodon'),
        (apps, 'ToneLib-GFX'),
        (apps, 'ToneLib-Zoom'),
        (apps, 'torchlight-2'),
        (apps, 'tormessenger'),
        (apps, 'torrserver'),
        (apps, 'tortoisehg'),
        (apps, 'tracktion'),
        (apps, 'tumblr'),
        (apps, 'tuxmath'),
        (apps, 'tuxtype'),
        (apps, 'twitter-x'),
        (apps, 'typecatcher'),
        (apps, 'typora'),
        (apps, 'ue4editor'),
        (apps, 'uk.co.mrbenshef.Boop-GTK'),
        (apps, 'ulauncher'),
        (apps, 'uno-calculator'),
        (apps, 'upsource'),
        (apps, 'upwork'),
        (apps, 'usbguard-icon'),
        (apps, 'utilities-terminal_su'),
        (apps, 'utilities-x-terminal'),
        (apps, 'vectr'),
        (apps, 'veloren'),
        (apps, 'veracrypt'),
        (apps, 'veusz'),
        (apps, 'vieb'),
        (apps, 'vifm'),
        (apps, 'vimeo'),
        (apps, 'vim'),
        (apps, 'virt-manager'),
        (apps, 'virtualbox'),
        (apps, 'vivaldi-beta'),
        (apps, 'vivaldi-snapshot'),
        (apps, 'vivaldi'),
        (apps, 'vmd'),
        (apps, 'vncviewer'),
        (apps, 'vnote'),
        (apps, 'vroid-studio'),
        (apps, 'warsow'),
        (apps, 'waterfox'),
        (apps, 'wavebox'),
        (apps, 'waveform11'),
        (apps, 'waydroid'),
        (apps, 'wayland'),
        (apps, 'Weasis'),
        (apps, 'webby'),
        (apps, 'webide'),
        (apps, 'webstorm'),
        (apps, 'welcome-screen'),
        (apps, 'WickrMe'),
        (apps, 'wikipedia'),
        (apps, 'windscribe'),
        (apps, 'wine-help'),
        (apps, 'wine-uninstaller'),
        (apps, 'wiznote'),
        (apps, 'wordpress'),
        (apps, 'workspace-overview'),
        (apps, 'wps-office2019-kprometheus'),
        (apps, 'wps-office-etmain'),
        (apps, 'wps-office-pdfmain'),
        (apps, 'wps-office-wppmain'),
        (apps, 'wps-office-wpsmain'),
        (apps, 'x2goclient'),
        (apps, 'fontypython'),
        (apps, 'xampp'),
        (apps, 'xash3d'),
        (apps, 'xchat'),
        (apps, 'xdiagnose'),
        (apps, 'xemu'),
        (apps, 'xenia'),
        (apps, 'xfce4-statusnotifier-plugin'),
        (apps, 'xfwm4'),
        (apps, 'xiaomitool'),
        (apps, 'xmind'),
        (apps, 'xmoto'),
        (apps, 'xneur'),
        (apps, 'xnoise'),
        (apps, 'xorg'),
        (apps, 'xournal'),
        (apps, 'XRCed'),
        (apps, 'xterm'),
        (apps, 'x-tile'),
        (apps, 'yahoo-mail'),
        (apps, 'yakuake'),
        (apps, 'yaourtgui'),
        (apps, 'yast-language'),
        (apps, 'yast-support'),
        (apps, 'yokadi'),
        (apps, 'youtrack'),
        (apps, 'y-ppa-manager'),
        (apps, 'yubikey-neo-manager'),
        (apps, 'yubikey-personalization-gui'),
        (apps, 'yubikey-piv-manager'),
        (apps, 'yubioath'),
        (apps, 'yuna'),
        (apps, 'zdoom'),
        (apps, 'zeal'),
        (apps, 'zed'),
        (apps, 'ZeroNet'),
        (apps, 'zevdocs'),
        (apps, 'ziggurat'),
        (apps, 'zint'),
        (apps, 'zotero'),
        (apps, 'zrythm'),
        (apps, 'zulip'),
        (apps, 'zuluCrypt'),
        (apps, 'zuluMount'),
    ]
}